// ui/src/components/Landing.vue
<template>
  <div class="columns">
    <div class="column">
        <form v-on:submit="createBattle">
            <b-field label="Your Name">
                <b-input v-model="creatorName" placeholder="Enter your name" required></b-input>
            </b-field>
            <b-field label="Battle Name">
                <b-input v-model="battleName" placeholder="Enter a battle name" required></b-input>
            </b-field>
            <button class="button is-primary">Create a Story Battle</button>
        </form>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Landing',
  methods: {
      createBattle: function (event) {
        event.preventDefault()
        const router = this.$router

        const {
            creatorName,
            battleName
        } = this

        fetch('/api/battle', {
            method: 'POST',
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify({
                creatorName,
                battleName
            })
        })
            .then(function(response) {
                return response.json()
            })
            .then(function(battle) {
                router.push(`/battle/${battle.id}`)
            });
        
    }
  },
  data() {
        return {
            creatorName: '',
            battleName: ''
        }
    }
}
</script>

// src/pages/Landing.svelte
<script>
    import { warrior } from '../stores.js'

    let battleName = ''

    function createBattle(e) {
        e.preventDefault()
        const data = {
            battleName,
            leaderId: $warrior.id
        }
        
        fetch('/api/battle', {
            method: 'POST',
            headers: {
                "Content-Type": "application/json"
            },
            body: JSON.stringify(data)
        })
            .then(function(response) {
                return response.json()
            })
            .then(function(battle) {
                window.location.href = `/battle/${battle.id}`
            });
    }
</script>

<form on:submit={createBattle} class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
    <div class="mb-4">
        <label class="block text-grey-darker text-sm font-bold mb-2" for="battleName">Battle Name</label>
        <div class="control">
            <input
                bind:value={battleName}
                placeholder="Enter a battle name"
                class="shadow appearance-none border rounded w-full py-2 px-3 text-grey-darker leading-tight focus:outline-none focus:shadow-outline"
                id="battleName"
                required
            />
        </div>
    </div>
    
    <div class="mb-6">
        <div class="flex items-center justify-between">
            <button class="bg-green hover:bg-green-dark text-white font-bold py-2 px-4 rounded" type="submit">Create a Story Battle</button>
        </div>
    </div>
</form>
