// ui/src/pages/Battle.svelte
<script>
    import { onDestroy } from 'svelte'
    import PointCard from '../components/PointCard.svelte'

    export let battleId = 0
    let points = ['1', '2', '3', '5', '8', '13', '?']
    let vote = '3'

    const socketExtension = window.location.protocol === 'https:' ? 'wss' : 'ws'

    const ws = new WebSocket(`${socketExtension}://${window.location.host}/api/battle/${battleId}`)

    let message = ''
    let responses = []

    ws.onmessage = function (evt) {
        responses[responses.length] = `${evt.data}`
    }

    ws.onerror = function (e) {
        console.log(`ERROR: ${e}`)
    }

    onDestroy(() => ws.close())

    function handleVote(event) {
        vote = event.detail.point
        ws.send(vote)
    }
</script>

<div class="columns">
    <div class="column">
        <h1 class="title">Battle: {battleId}</h1>

        <div class="columns">
            {#each points as point}
                <div class="column">
                    <PointCard point={point} active={vote === point} on:voted={handleVote} />
                </div>
            {/each}
        </div>
    </div>
    <div class="column">            
        <h2>Votes:</h2>

        {#each responses as response}
            <div class="notification is-success">
                {response}
            </div>
        {/each}
    </div>
  </div>

// ui/src/components/Battle.vue
<template>
  <div class="columns">
    <div class="column">
        <h1>Battle: {{ $route.params.id }}</h1>
        <p>Click "Send" to send a message to the server.<br />
        You can change the message and send multiple times.
        </p>

        <form>
            <b-field label="Name">
                <b-input v-model="name" id="input"></b-input>
            </b-field>
            <button class="button is-success" v-on:click="sendMessage">Send</button>
        </form>
    </div>
    <div class="column">            
        <div id="output"></div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Battle',
  data() {
    return {
        name: 'Thunderdome',
        ws: null
    }
  },
  created: function () {
      this.ws = new WebSocket("ws://localhost:8080/api/battle/1");

      this.ws.onmessage = function (evt) {
        console.log("RESPONSE: " + evt.data);
      }
      this.ws.onerror = function (evt) {
        console.log("ERROR: " + evt.data);
      }
  },
  beforeDestroy: function () {
      this.ws.close()
  },
  methods: {
      sendMessage: function (event) {
        event.preventDefault()

        console.log("SEND: " + input.value);
        this.ws.send(input.value);
      }
  }
}
</script>
