// ui/src/pages/battle.svelte
<script>
    import { onDestroy } from 'svelte'

    export let battleId = 0

    const ws = new WebSocket(`ws://${window.location.host}/api/battle/${battleId}`)

    let message = ''
    let responseOutput = ''

    ws.onmessage = function (evt) {
        responseOutput = `RESPONSE: ${evt.data}`
    }

    ws.onerror = function (e) {
        responseOutput = `ERROR: ${e}`
    }

    function sendMessage(e) {
        e.preventDefault()
        console.log("SEND: " + message)
            
        ws.send(message)
    }

    onDestroy(() => ws.close())
</script>

<div class="columns">
    <div class="column">
        <h1>Battle: {battleId}</h1>
        <p>
            Click "Send" to send a message to the server.<br />
            You can change the message and send multiple times.
        </p>

        <form on:submit={sendMessage}>
            <div class="field">
                <label class="label">Message</label>
                <div class="control">
                    <input bind:value={message} placeholder="Enter a message" class="input" required />
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <button class="button is-success" type="submit">Send</button>
                </div>
            </div>
        </form>
    </div>
    <div class="column">            
        <p>{responseOutput}</p>
    </div>
  </div>

// ui/src/components/Battle.vue
<template>
  <div class="columns">
    <div class="column">
        <h1>Battle: {{ $route.params.id }}</h1>
        <p>Click "Send" to send a message to the server.<br />
        You can change the message and send multiple times.
        </p>

        <form>
            <b-field label="Name">
                <b-input v-model="name" id="input"></b-input>
            </b-field>
            <button class="button is-success" v-on:click="sendMessage">Send</button>
        </form>
    </div>
    <div class="column">            
        <div id="output"></div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Battle',
  data() {
    return {
        name: 'Thunderdome',
        ws: null
    }
  },
  created: function () {
      this.ws = new WebSocket("ws://localhost:8080/api/battle/1");

      this.ws.onmessage = function (evt) {
        console.log("RESPONSE: " + evt.data);
      }
      this.ws.onerror = function (evt) {
        console.log("ERROR: " + evt.data);
      }
  },
  beforeDestroy: function () {
      this.ws.close()
  },
  methods: {
      sendMessage: function (event) {
        event.preventDefault()

        console.log("SEND: " + input.value);
        this.ws.send(input.value);
      }
  }
}
</script>
